package network;

import java.util.LinkedList;

public interface ServerInteractionInterface {

    //
    //	The writeToServer method is meant to respond to events associated with,
    //		or actions generated by, an Alarm.
    //

    void writeToServer(int command);

    void writeToServer(int command, LinkedList<String> data);
}


